### ISSUE TITLE
How to get actual AES pass key?

### ISSUE THREAD

**Issue by bartwind** [Mila432/King-of-Avalon-Dragon-Warfare-Python-Bot#4]
Hi buddy,
how can I get actual version AES pass key from client? I want start work on PHP bot..

**Comment by Mila432** [comment]
extract it

**Comment by bartwind** [comment]
Thanks for reply any clue how to do this? How you did this for your version? Debugged APK? or extracted APK?

**Comment by bartwind** [comment]
Please can you say me buddy how you did that to old version? I want just know if its still possible for new version? My mail: bartkoa8221@gmail.com
Thx!
